### ISSUE TITLE
Multiple client connection

### ISSUE THREAD

**Issue by katyo** [finchers-rs/finchers#173] opened 2018-04-07 07:21 UTC
I cannot connect to example application from readme twice and more times.
It seems the problem with accepting client connections.

**Comment by ubnt-intrepid** [comment] 2018-04-07 07:29
I didn't reproduce the issue in my environment.
Could you complement your env?

**Comment by ubnt-intrepid** [comment] 2018-10-09 09:54
I close this issue because the HTTP server was completely replaced to the new implementation.

**Closed by ubnt-intrepid** 2018-10-09 09:54 UTC
